### ISSUE TITLE
Possible for Video Playlists?

### ISSUE THREAD

**Issue by SirBassi** [swolekat/obs-youtube-playlist-title#1]
Hi Swolekat,

I am not so familar with Github and so not quite sure if my question is a "Issue" or a "Pull Request". 
First of all your tool for bringing the YT Title to OBS is quite awesome. 
But I wanna kindly ask if it is also possible to show up the video files if your tool is used with a video playlist instead of a music playlist.

I think on using it in a break scenze scenario or stream ended case.

Thanks a lot for letting me know.

**Comment by swolekat** [comment]
Hello, I'm not sure I entirely understand your request.

If you're asking to show the youtube video itself I guess that wouldn't be too hard to do although I'm not sure if another solution exists that might be better.

If you're asking for supporting local files that's probably outside of the scope of the project since it's based on embedding a youtube player. 

Oddly enough I did do a similar project for showing random twitch clips here that you might find useful: https://github.com/swolekat/se-widgets/tree/main/continuous-clip-player

**Comment by SirBassi** [comment]
Hi,

Thank you for your quick response.

If I understood correctly, you designed your tool for
- Playing music YT playlist
- Displaying author + title of the current title from the YT playlist
- Since it is music, no image is transmitted

I would really like to integrate the tool into the stream because I use video playlists from my own YT channel in certain scenes.

However, I would need the image to be displayed from the YT Playlist (no offline sources), as well as the title and author, of course.

I have spent the whole weekend researching Github, OBS forum and various YouTube guides, but your tool approach seems to be the very best for implementing it.

If you see a possibility, I would be very happy.

**Comment by swolekat** [comment]
@SirBassi I just pushed a new version that now accepts `video=true` in the query paramater. It should show the video. I think this is what you're looking for. 

Example usage:
```
https://swolekat.github.io/obs-youtube-playlist-title/?v=I9kC5ZxDQ9E&list=PL8dcsJNXFe0Qndwgrrax091jhU7xNrKhG&index=1&video=true
```

**Comment by SirBassi** [comment]
Thank you for the quick solution.
It works as intended, but the YouTube API seems to be blocking it. The video loads briefly and then there is an endless loop. It's as if the video can't be buffered properly.
But of course that's not your fault and maybe Google will find a solution.

As a workaround, I'll play the video playlist directly in the local browser and capture the window and use your tool to display the title.

Thank you again.

**Comment by SirBassi** [comment]
I found it out. When I uncheck the browser source hardware acceleration ist works perfect.

Just one final question: Is there maybe a command to fade out the scroll bar on the side?
Attach a Sreenshot from the preview of the Source.
![1](https://github.com/user-attachments/assets/623e6462-c6d9-4bf1-9d96-7e043e99b5d1)

**Comment by swolekat** [comment]
@SirBassi can you try adding this custom css in obs and let me know if it works? If it does I'll add it in by default
```
* { overflow: hidden; }
```

**Comment by SirBassi** [comment]
Yes, this works very perfect.
Everything is running now as I wished as I started to search about this topic.

Absolute amazing your help, I am deeply thankful.
